name: Deploy EKS Infrastructure

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  terraform-plan:
    name: " Terraform Plan"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: " Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: " Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: " Terraform Init"
        run: terraform init
        working-directory: terraform # ← Points to terraform folder

      - name: " Terraform Validate"
        run: terraform validate
        working-directory: terraform # ← Points to terraform folder

      - name: " Terraform Plan"
        run: terraform plan
        working-directory: terraform # ← Points to terraform folder

  terraform-apply:
    name: " Terraform Apply"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: " Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: " Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: " Terraform Init"
        run: terraform init
        working-directory: terraform
